version: "3.8"

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    restart: always
    environment:
      - JWT_SECRET=3830625c7ce54e0e5bec5a226b5f89f82c22554757bb0e955835a3231c6864ba
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=user:password@tcp(db:3306)/url_scraper?parseTime=true
    depends_on:
      - db
    restart: always
  db:
    image: mysql:9
    ports:
      - "13306:3306"
    environment:
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_scraper
    restart: always
