version: "3.8"

services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/url_scraper?parseTime=true
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_scraper
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
